apiVersion: v1
kind: Secret
metadata:
  name: secrets
type: Opaque
data:
  JWT_SECRET: aC27ziSWlgWVWQqkfBaJ58CYQQhcr+tAAsOZXZ6kgDU=
  JWT_REFRESH_SECRET: ammngMqPcqasE5TtUfM9MTanQvxGSTNcDNdaotrEFkLj3aAIZeVikcDW1Q3Ww1hhfN6NsQpPnGvjpIsEp5nAsA==
  GEMINI_API_KEY: QUl6YVN5QlMzNy1nMkwyRWtaRmYwTzl5MmptVDhKOG4tbWVkUjNZ
  MISTRAL_API_KEY: MfpCP1mANc9bYmDgASru2eYZeuUmBPfA


