apiVersion: v1
kind: Secret
metadata:
  name: jwt-secrets
type: Opaque
data:
  JWT_SECRET: aC27ziSWlgWVWQqkfBaJ58CYQQhcr+tAAsOZXZ6kgDU=
  JWT_REFRESH_SECRET: ammngMqPcqasE5TtUfM9MTanQvxGSTNcDNdaotrEFkLj3aAIZeVikcDW1Q3Ww1hhfN6NsQpPnGvjpIsEp5nAsA==
